import type { MetadataRoute } from "next";
import { siteUrl } from "@/lib/seo";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [{
      userAgent: ["Googlebot", "Bingbot", "*"],
      allow: ["/", "/home", "/about", "/contact", "/faq", "/find-coach", "/coaches/", "/dojos/", "/shop", "/products/", "/seller", "/policies/", "/privacy", "/terms"],
      disallow: [
        "/admin",
        "/owner",
        "/super-admin-dashboard",
        "/dashboard",
        "/seller-dashboard",
        "/coach-dashboard",
        "/dojo-dashboard",
        "/api",
        "/auth",
        "/profile",
        "/settings",
        "/chat",
        "/orders",
        "/wallet",
        "/checkout",
        "/cart",
        "/invites",
        "/attendance",
        "/verification",
        "/complete-profile",
        "/life",
        "/booking",
        "/become-a-coach",
        "/register-dojo",
        "/register-seller",
        "/seller/register",
        "/setup",
        "/login",
        "/signup",
        "/forgot-password",
        "/account",
        "/payment",
        "/test",
        "/tests",
        "/dev",
        "/preview",
      ],
    }],
    sitemap: `${siteUrl}/sitemap.xml`,
    host: siteUrl,
  };
}
