"use client";

/* eslint-disable @next/next/no-img-element -- social images are served by the authenticated local API */
import { BadgeCheck, MapPin, MessageCircle } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { socialApi, socialAsset, type SocialProfile } from "@/lib/social";

export function SocialProfileCard({ profile }: { profile: SocialProfile }) {
  const [status, setStatus] = useState("");
  async function invite() { try { await socialApi("/invites", { method: "POST", body: JSON.stringify({ recipientId: profile.id, message: `Let's connect through our shared fitness interests.` }) }); setStatus("Invite sent"); } catch (error) { setStatus(error instanceof Error ? error.message : "Invite failed"); } }
  return <article className="group overflow-hidden rounded-[1.7rem] border border-white/10 bg-white/[.05] transition hover:-translate-y-1 hover:border-acid/40"><Link href={`/life/${profile.id}`} className="block"><div className="relative aspect-[4/3] overflow-hidden bg-gradient-to-br from-acid/10 to-royal/10">{profile.photos?.[0]?<img src={socialAsset(profile.photos[0])} alt={profile.name} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="grid h-full place-items-center text-5xl font-black text-white/15">{profile.name.slice(0,1)}</div>}<div className="absolute left-4 top-4 flex gap-2">{profile.verified?<Tag><BadgeCheck className="h-3 w-3"/>Verified</Tag>:null}</div>{profile.online?<span className="absolute bottom-4 right-4 inline-flex items-center gap-2 rounded-full bg-ink/80 px-3 py-1 text-xs text-acid"><span className="h-2 w-2 rounded-full bg-acid"/>Online</span>:null}</div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold text-white">{profile.name}{profile.age?`, ${profile.age}`:""}</h2><p className="mt-1 inline-flex items-center gap-1 text-sm text-zinc-400"><MapPin className="h-4 w-4"/>{profile.city||"India"}{profile.distanceKm!=null?` · ${profile.distanceKm} km`:""}</p></div>{profile.compatibility!=null?<div className="rounded-xl bg-acid/10 px-3 py-2 text-center"><p className="font-black text-acid">{profile.compatibility}%</p><p className="text-[10px] text-zinc-500">match</p></div>:null}</div><div className="mt-4 flex flex-wrap gap-2">{profile.interests?.slice(0,4).map(item=><span key={item} className="rounded-full border border-white/10 px-2.5 py-1 text-xs text-zinc-300">{item}</span>)}</div><p className="mt-4 line-clamp-2 text-sm leading-6 text-zinc-400">{profile.profileBio||profile.fitnessGoal||"Ready to find a committed fitness partner."}</p></div></Link><div className="border-t border-white/10 p-4"><button onClick={invite} disabled={Boolean(status)} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-acid px-4 py-3 text-sm font-bold text-ink disabled:bg-white/10 disabled:text-zinc-400"><MessageCircle className="h-4 w-4"/>{status||"Send invite"}</button></div></article>;
}
function Tag({children}:{children:React.ReactNode}){return <span className="inline-flex items-center gap-1 rounded-full border border-acid/30 bg-ink/80 px-2.5 py-1 text-xs font-semibold text-acid">{children}</span>}
